apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-backend-bitbucket-template
  title: Create a Node.js Backend application with Bitbucket and CI pipeline
  description: Create a starter Node.js backend application with Bitbucket repository and CI pipeline
  tags:
    - recommended
    - bitbucket
    - nodejs
    - javascript
    - typescript
    - express
spec:
  owner: platform-team
  system: cnoe-platform
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - workspace
        - repoName
        - owner
        - system
        - port
      properties:
        workspace:
          title: Bitbucket Workspace
          type: string
          description: The Bitbucket workspace where the repository will be created
          default: your-workspace
        repoName:
          title: Repository Name
          type: string
          description: The name of the repository
          pattern: '^[a-z0-9-]+$'
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 3000
          description: Override the port exposed for the application
    - title: Provide information about the CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          description: This action will create a CI pipeline for your application based on chosen method
          default: ../../../skeletons/bitbucket-pipelines/
          enum:
            - ../../../skeletons/bitbucket-pipelines/
            - ../../../skeletons/github-actions/
          enumNames:
            - Bitbucket Pipelines
            - GitHub Actions (for reference)
      dependencies:
        ci:
          oneOf:
            - properties:
                # Show no extra properties when Bitbucket Pipelines is selected
                ci:
                  const: ../../../skeletons/bitbucket-pipelines/
            - required:
                - imageRepository
                - namespace
                - imageUrl
              properties:
                ci:
                  const: ../../../skeletons/github-actions/
                imageRepository:
                  title: Select a registry
                  type: string
                  default: docker.io
                  enum:
                    - docker.io
                    - quay.io
                  enumNames:
                    - Docker Hub
                    - Quay.io
                imageUrl:
                  title: Image URL
                  type: string
                  description: The Docker registry URL <REGISTRY>/<IMAGE_URL>/<REPO_NAME>
                namespace:
                  title: Namespace
                  type: string
                  description: The namespace for deploying resources
  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          workspace: ${{ parameters.workspace }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-nodejs
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          sourceControl: bitbucket.org

    - id: ciTemplate
      name: Generating the CI Component
      action: fetch:template
      input:
        url: ${{ parameters.ci }}
        copyWithoutTemplating:
          - bitbucket-pipelines.yml
        values:
          workspace: ${{ parameters.workspace }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-nodejs
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          sourceControl: bitbucket.org

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../../skeletons/catalog-info/
        values:
          workspace: ${{ parameters.workspace }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-nodejs
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          sourceControl: bitbucket.org

    - id: publish
      name: Publishing to Bitbucket Repository
      action: publish:bitbucket
      input:
        description: ${{ parameters.description }}
        repoUrl: bitbucket.org?workspace=${{ parameters.workspace }}&repo=${{ parameters.repoName }}
        defaultBranch: main
        gitAuthorName: Backstage
        gitAuthorEmail: backstage@example.com

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Bitbucket Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}