---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitbucket-integration
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: bitbucket-integration
    template:
      data:
        bitbucket-integration.yaml: |
          server: {{ .server_url }}
          username: {{ .username }}
          appPassword: {{ .app_password }}
  data:
  - secretKey: "server_url"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/bitbucket-app
      metadataPolicy: None
      property: server_url
  - secretKey: "username"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/bitbucket-app
      metadataPolicy: None
      property: username
  - secretKey: "app_password"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/bitbucket-app
      metadataPolicy: None
      property: app_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitbucket-env-vars
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: bitbucket-env-vars
    creationPolicy: "Merge"
    template:
      data:
        BITBUCKET_USERNAME: "{{ .username }}"
        BITBUCKET_APP_PASSWORD: "{{ .app_password }}"
        BITBUCKET_SERVER_URL: "{{ .server_url }}"
        BITBUCKET_WORKSPACE: "{{ .workspace }}"
  data:
  - secretKey: "username"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/bitbucket-app
      metadataPolicy: None
      property: username
  - secretKey: "app_password"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/bitbucket-app
      metadataPolicy: None
      property: app_password
  - secretKey: "server_url"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/bitbucket-app
      metadataPolicy: None
      property: server_url
  - secretKey: "workspace"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/bitbucket-app
      metadataPolicy: None
      property: workspace