apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-postgres-operator
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cnpg-system
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: 'https://cloudnative-pg.github.io/charts'
      targetRevision: 0.22.1
      chart: cloudnative-pg
      helm:
        releaseName: cloudnative-pg-operator
        skipCrds: false
        valueFiles:
          - $values/values.yaml
    - repoURL: cnoe://cloudnative-postgres-operator/manifests
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true